export const LedgerEvent = {
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",

  ESCROW_HELD: "ESCROW_HELD",

  ESCROW_RELEASED: "ESCROW_RELEASED",

  PLATFORM_FEE: "PLATFORM_FEE",

  REFUND_ISSUED: "REFUND_ISSUED",

  PAYOUT_SENT: "PAYOUT_SENT",

  SUBSCRIPTION_RENEWED: "SUBSCRIPTION_RENEWED",

  LOAN_DISBURSED: "LOAN_DISBURSED",

  LOAN_REPAYMENT: "LOAN_REPAYMENT",

  VENDOR_SHARE: "VENDOR_SHARE",

  PLATFORM_SHARE: "PLATFORM_SHARE",

  FRAUD_FLAGGED: "FRAUD_FLAGGED",
} as const;